//! Structured request/response logging.
//!
//! Writes each interaction to SQLite (primary) and optionally mirrors to JSONL (human-grep).
//! The goal is to make threat-intel analysis trivial: `sqlite3 hive.db 'select ...'` or `jq`
//! over the JSONL tail — no custom tooling required.
//!
//! Postgres backend is available under `--features postgres`; see the
//! [`postgres`] module. Migrations live in `migrations/*.sql`.

#[cfg(feature = "postgres")]
pub mod postgres;

pub mod operator;
pub use operator::OperatorClassifier;

use anyhow::{Context, Result};
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;

use crate::canary::{CanaryHit, CanaryImportSummary};
use crate::detect::Detection;

/// A single request/response interaction that we persist for later analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEntry {
    pub timestamp_ms: i64,
    pub method: String,
    pub params_hash: String,
    pub params: Option<Value>,
    pub client_name: Option<String>,
    pub client_version: Option<String>,
    pub session_id: String,
    pub response_summary: String,
    #[serde(default)]
    pub transport: Option<String>,
    #[serde(default)]
    pub remote_addr: Option<String>,
    #[serde(default)]
    pub user_agent: Option<String>,
    #[serde(default)]
    pub client_meta: Option<Value>,
    /// Name of the persona that served this request. Set by the dispatcher
    /// after resolving the route key, so the dashboard can show — and filter
    /// by — which honeypot face the attacker hit.
    #[serde(default)]
    pub persona: Option<String>,
    /// True when this event was generated by the operator running the
    /// honeypot (probes, validation curls, allowlisted IPs). Default false
    /// so legacy callers and JSONL re-ingest both stay honest.
    #[serde(default)]
    pub is_operator: bool,
}

pub fn hash_params(params: &Option<Value>) -> String {
    let mut hasher = Sha256::new();
    match params {
        Some(v) => {
            let canonical = serde_json::to_vec(v).unwrap_or_default();
            hasher.update(&canonical);
        }
        None => hasher.update(b""),
    }
    hex::encode(hasher.finalize())
}

/// Combined SQLite+JSONL logger. Clonable via Arc so multiple tasks can share it.
#[derive(Clone)]
pub struct Logger {
    inner: Arc<LoggerInner>,
}

/// Hard upper bound on the events table. When we exceed it, the oldest 10%
/// of events are dropped (and their detections cascade via ON DELETE CASCADE).
/// This prevents a disk-fill denial-of-service against a cheap VPS at the cost
/// of eventually losing the earliest captures. For threat-intel use, recent is
/// more valuable than complete, so the tradeoff is deliberate.
const MAX_EVENTS: i64 = 1_000_000;
const EVENTS_TRIM_BATCH: i64 = 100_000;

/// Cap on a single params payload. Values longer than this are truncated on
/// insert. A legitimate MCP tool call carries at most a few KB of arguments;
/// anything larger is an attacker trying to blow up the database.
const MAX_PARAMS_BYTES: usize = 64 * 1024;

struct LoggerInner {
    db: Mutex<Connection>,
    jsonl: Mutex<Option<tokio::fs::File>>,
    jsonl_path: Option<PathBuf>,
}

impl Logger {
    pub async fn open(db_path: &Path, jsonl_path: Option<&Path>) -> Result<Self> {
        if let Some(parent) = db_path.parent() {
            if !parent.as_os_str().is_empty() {
                tokio::fs::create_dir_all(parent).await.ok();
            }
        }
        let db = Connection::open(db_path)
            .with_context(|| format!("opening sqlite db at {}", db_path.display()))?;
        db.execute_batch(
            r#"
            CREATE TABLE IF NOT EXISTS events (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp_ms    INTEGER NOT NULL,
                session_id      TEXT    NOT NULL,
                method          TEXT    NOT NULL,
                params_hash     TEXT    NOT NULL,
                params          TEXT,
                client_name     TEXT,
                client_version  TEXT,
                response_summary TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_events_method    ON events(method);
            CREATE INDEX IF NOT EXISTS idx_events_session   ON events(session_id);
            CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp_ms);

            CREATE TABLE IF NOT EXISTS detections (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                event_id      INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                timestamp_ms  INTEGER NOT NULL,
                detector      TEXT    NOT NULL,
                severity      TEXT    NOT NULL,
                category      TEXT    NOT NULL,
                evidence      TEXT    NOT NULL,
                notes         TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_detections_event    ON detections(event_id);
            CREATE INDEX IF NOT EXISTS idx_detections_category ON detections(category);
            CREATE INDEX IF NOT EXISTS idx_detections_severity ON detections(severity);

            CREATE TABLE IF NOT EXISTS canary_exposures (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                event_id      INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                timestamp_ms  INTEGER NOT NULL,
                marker        TEXT    NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS idx_canary_exposures_event_marker
                ON canary_exposures(event_id, marker);
            CREATE INDEX IF NOT EXISTS idx_canary_exposures_marker
                ON canary_exposures(marker);
            CREATE INDEX IF NOT EXISTS idx_canary_exposures_timestamp
                ON canary_exposures(timestamp_ms);

            CREATE TABLE IF NOT EXISTS canary_hits (
                id                    INTEGER PRIMARY KEY AUTOINCREMENT,
                observed_at_ms        INTEGER NOT NULL,
                token_type            TEXT,
                provider_event        TEXT,
                later_token_use_ip    TEXT,
                user_agent            TEXT,
                account_id            TEXT,
                input_channel         TEXT,
                alert_status          TEXT,
                marker                TEXT,
                geo_json              TEXT,
                raw_hash              TEXT    NOT NULL UNIQUE
            );
            CREATE INDEX IF NOT EXISTS idx_canary_hits_observed
                ON canary_hits(observed_at_ms);
            CREATE INDEX IF NOT EXISTS idx_canary_hits_marker
                ON canary_hits(marker);
            CREATE INDEX IF NOT EXISTS idx_canary_hits_later_ip
                ON canary_hits(later_token_use_ip);
            "#,
        )
        .context("initializing events + detections schema")?;

        // Backward-compatible column additions. SQLite has no ALTER TABLE ... ADD COLUMN
        // IF NOT EXISTS, so we inspect pragma_table_info and add only what's missing.
        add_column_if_missing(&db, "events", "transport", "TEXT")?;
        add_column_if_missing(&db, "events", "remote_addr", "TEXT")?;
        add_column_if_missing(&db, "events", "user_agent", "TEXT")?;
        add_column_if_missing(&db, "events", "client_meta", "TEXT")?;
        add_column_if_missing(&db, "events", "persona", "TEXT")?;
        add_column_if_missing(&db, "events", "is_operator", "INTEGER NOT NULL DEFAULT 0")?;
        // JSON-encoded array of MITRE ATT&CK / ATLAS technique IDs the
        // detector mapped to. NULL when the detector emitted no mapping.
        // Stored as TEXT (not a separate join table) so SIEM exporters
        // can pull the column verbatim into STIX 2.1 / OpenSearch docs.
        add_column_if_missing(&db, "detections", "mitre_techniques", "TEXT")?;

        let jsonl = match jsonl_path {
            Some(p) => {
                if let Some(parent) = p.parent() {
                    if !parent.as_os_str().is_empty() {
                        tokio::fs::create_dir_all(parent).await.ok();
                    }
                }
                let f = tokio::fs::OpenOptions::new()
                    .create(true)
                    .append(true)
                    .open(p)
                    .await
                    .with_context(|| format!("opening jsonl at {}", p.display()))?;
                Some(f)
            }
            None => None,
        };

        Ok(Self {
            inner: Arc::new(LoggerInner {
                db: Mutex::new(db),
                jsonl: Mutex::new(jsonl),
                jsonl_path: jsonl_path.map(Path::to_path_buf),
            }),
        })
    }

    pub fn jsonl_path(&self) -> Option<&Path> {
        self.inner.jsonl_path.as_deref()
    }

    /// Insert the event and return its row id so callers can attach related detections.
    pub async fn record(&self, entry: &LogEntry) -> Result<i64> {
        let event_id = {
            let db = self.inner.db.lock().await;
            let params_str = entry.params.as_ref().map(|v| {
                let s = serde_json::to_string(v).unwrap_or_default();
                if s.len() > MAX_PARAMS_BYTES {
                    // Preserve a marker so downstream analysis knows why the
                    // payload is short. SQLite storage + future tail queries
                    // both stay bounded.
                    format!(
                        "{{\"_truncated\":true,\"_original_bytes\":{}, \"_prefix\":{}}}",
                        s.len(),
                        serde_json::Value::String(s.chars().take(2048).collect::<String>())
                    )
                } else {
                    s
                }
            });
            let client_meta_str = entry
                .client_meta
                .as_ref()
                .map(|v| serde_json::to_string(v).unwrap_or_default());
            db.execute(
                "INSERT INTO events
                    (timestamp_ms, session_id, method, params_hash, params,
                     client_name, client_version, response_summary,
                     transport, remote_addr, user_agent, client_meta, persona, is_operator)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)",
                params![
                    entry.timestamp_ms,
                    entry.session_id,
                    entry.method,
                    entry.params_hash,
                    params_str,
                    entry.client_name,
                    entry.client_version,
                    entry.response_summary,
                    entry.transport,
                    entry.remote_addr,
                    entry.user_agent,
                    client_meta_str,
                    entry.persona,
                    entry.is_operator as i64,
                ],
            )
            .context("inserting event row")?;
            let id = db.last_insert_rowid();

            // Opportunistic ring-buffer: every 1,000 inserts, check total size
            // and trim the oldest batch if we're past MAX_EVENTS. Keeps the DB
            // bounded without running on every single insert.
            if id % 1000 == 0 {
                if let Ok(count) =
                    db.query_row::<i64, _, _>("SELECT COUNT(*) FROM events", [], |r| r.get(0))
                {
                    if count > MAX_EVENTS {
                        let _ = db.execute(
                            "DELETE FROM events WHERE id IN (
                                 SELECT id FROM events ORDER BY id ASC LIMIT ?1
                             )",
                            params![EVENTS_TRIM_BATCH],
                        );
                    }
                }
            }
            id
        };

        let mut jsonl = self.inner.jsonl.lock().await;
        if let Some(f) = jsonl.as_mut() {
            let mut line = serde_json::to_vec(entry).context("serializing jsonl entry")?;
            line.push(b'\n');
            f.write_all(&line).await.context("appending to jsonl")?;
            f.flush().await.ok();
        }
        Ok(event_id)
    }

    pub async fn record_detections(
        &self,
        event_id: i64,
        timestamp_ms: i64,
        detections: &[Detection],
    ) -> Result<()> {
        if detections.is_empty() {
            return Ok(());
        }
        let db = self.inner.db.lock().await;
        let mut stmt = db
            .prepare_cached(
                "INSERT INTO detections (event_id, timestamp_ms, detector, severity, category, evidence, notes, mitre_techniques)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            )
            .context("preparing detection insert")?;
        for d in detections {
            // Empty slice -> NULL so SIEM consumers can filter on "has mapping"
            // with a plain IS NOT NULL predicate. JSON array otherwise.
            let techniques_json = if d.mitre_techniques.is_empty() {
                None
            } else {
                Some(
                    serde_json::to_string(d.mitre_techniques)
                        .context("serializing mitre techniques")?,
                )
            };
            stmt.execute(params![
                event_id,
                timestamp_ms,
                d.detector,
                d.severity.as_str(),
                d.category.as_str(),
                d.evidence,
                d.notes,
                techniques_json,
            ])
            .context("inserting detection row")?;
        }
        Ok(())
    }

    pub async fn record_canary_exposures(
        &self,
        event_id: i64,
        timestamp_ms: i64,
        markers: &[String],
    ) -> Result<()> {
        if markers.is_empty() {
            return Ok(());
        }
        let db = self.inner.db.lock().await;
        let mut stmt = db
            .prepare_cached(
                "INSERT OR IGNORE INTO canary_exposures
                    (event_id, timestamp_ms, marker)
                 VALUES (?1, ?2, ?3)",
            )
            .context("preparing canary exposure insert")?;
        for marker in markers {
            stmt.execute(params![event_id, timestamp_ms, marker])
                .context("inserting canary exposure row")?;
        }
        Ok(())
    }

    pub async fn import_canary_hits(&self, hits: &[CanaryHit]) -> Result<CanaryImportSummary> {
        let db = self.inner.db.lock().await;
        let mut inserted = 0usize;
        let mut ignored = 0usize;
        let mut stmt = db
            .prepare_cached(
                "INSERT OR IGNORE INTO canary_hits
                    (observed_at_ms, token_type, provider_event, later_token_use_ip,
                     user_agent, account_id, input_channel, alert_status, marker,
                     geo_json, raw_hash)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
            )
            .context("preparing canary hit insert")?;
        for hit in hits {
            let geo_json = hit
                .geo_json
                .as_ref()
                .map(|v| serde_json::to_string(v).unwrap_or_default());
            let n = stmt
                .execute(params![
                    hit.observed_at_ms,
                    hit.token_type.as_deref(),
                    hit.provider_event.as_deref(),
                    hit.later_token_use_ip.as_deref(),
                    hit.user_agent.as_deref(),
                    hit.account_id.as_deref(),
                    hit.input_channel.as_deref(),
                    hit.alert_status.as_deref(),
                    hit.marker.as_deref(),
                    geo_json,
                    hit.raw_hash.as_str(),
                ])
                .context("inserting canary hit row")?;
            if n == 0 {
                ignored += 1;
            } else {
                inserted += 1;
            }
        }
        Ok(CanaryImportSummary {
            total: hits.len(),
            inserted,
            ignored,
        })
    }

    pub async fn canary_backfill_events(&self) -> Result<Vec<CanaryBackfillEvent>> {
        let db = self.inner.db.lock().await;
        let mut stmt = db
            .prepare(
                "SELECT id, timestamp_ms, persona, params
                 FROM events
                 WHERE method = 'tools/call'
                 ORDER BY id ASC",
            )
            .context("preparing canary backfill query")?;
        let rows = stmt
            .query_map([], |r| {
                Ok(CanaryBackfillEvent {
                    event_id: r.get(0)?,
                    timestamp_ms: r.get(1)?,
                    persona: r.get(2)?,
                    params: r.get(3)?,
                })
            })?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    pub async fn recent_canary_correlations(
        &self,
        since_hit_ms: i64,
        max_delay_ms: i64,
        limit: i64,
        include_operator: bool,
    ) -> Result<Vec<CanaryCorrelationRow>> {
        let db = self.inner.db.lock().await;
        let op_filter = if include_operator {
            ""
        } else {
            "AND e.is_operator = 0"
        };
        let sql = format!(
            "SELECT
               h.id,
               h.observed_at_ms,
               h.token_type,
               h.provider_event,
               h.later_token_use_ip,
               h.user_agent,
               h.account_id,
               h.marker,
               ce.marker,
               e.id,
               e.timestamp_ms,
               e.remote_addr,
               e.persona,
               e.method,
               e.params,
               e.response_summary,
               h.observed_at_ms - e.timestamp_ms AS delay_ms
             FROM canary_hits h
             JOIN canary_exposures ce
               ON h.marker IS NULL OR h.marker = ce.marker
             JOIN events e
               ON e.id = ce.event_id
             WHERE h.observed_at_ms >= ?1
               AND e.timestamp_ms <= h.observed_at_ms
               AND h.observed_at_ms - e.timestamp_ms <= ?2
               {op_filter}
             ORDER BY h.observed_at_ms DESC, delay_ms ASC, e.id DESC
             LIMIT ?3"
        );
        let mut stmt = db.prepare(&sql)?;
        let rows = stmt
            .query_map(params![since_hit_ms, max_delay_ms, limit], |r| {
                Ok(CanaryCorrelationRow {
                    hit_id: r.get(0)?,
                    hit_timestamp_ms: r.get(1)?,
                    token_type: r.get(2)?,
                    provider_event: r.get(3)?,
                    later_token_use_ip: r.get(4)?,
                    hit_user_agent: r.get(5)?,
                    account_id: r.get(6)?,
                    hit_marker: r.get(7)?,
                    canary_marker: r.get(8)?,
                    event_id: r.get(9)?,
                    exposure_timestamp_ms: r.get(10)?,
                    exposure_source_ip: r.get(11)?,
                    persona: r.get(12)?,
                    method: r.get(13)?,
                    params: r.get(14)?,
                    response_summary: r.get(15)?,
                    delay_ms: r.get(16)?,
                })
            })?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    pub async fn count_events(&self, include_operator: bool) -> Result<i64> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT COUNT(*) FROM events"
        } else {
            "SELECT COUNT(*) FROM events WHERE is_operator = 0"
        };
        let n: i64 = db.query_row(sql, [], |r| r.get(0))?;
        Ok(n)
    }

    pub async fn events_by_method(&self, include_operator: bool) -> Result<Vec<(String, i64)>> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT method, COUNT(*) FROM events GROUP BY method ORDER BY 2 DESC"
        } else {
            "SELECT method, COUNT(*) FROM events
             WHERE is_operator = 0 GROUP BY method ORDER BY 2 DESC"
        };
        let mut stmt = db.prepare(sql)?;
        let rows = stmt
            .query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?)))?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    pub async fn unique_remote_addrs_since(
        &self,
        since_ms: i64,
        include_operator: bool,
    ) -> Result<i64> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT COUNT(DISTINCT remote_addr) FROM events
             WHERE remote_addr IS NOT NULL AND timestamp_ms >= ?1"
        } else {
            "SELECT COUNT(DISTINCT remote_addr) FROM events
             WHERE remote_addr IS NOT NULL AND timestamp_ms >= ?1
                   AND is_operator = 0"
        };
        let n: i64 = db.query_row(sql, params![since_ms], |r| r.get(0))?;
        Ok(n)
    }

    pub async fn detections_by_category(
        &self,
        include_operator: bool,
    ) -> Result<Vec<(String, i64)>> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT d.category, COUNT(*) FROM detections d
             GROUP BY d.category ORDER BY 2 DESC"
        } else {
            // Operator-tagged events get filtered via the join — detections
            // inherit operator-ness from their parent event.
            "SELECT d.category, COUNT(*) FROM detections d
             JOIN events e ON e.id = d.event_id
             WHERE e.is_operator = 0
             GROUP BY d.category ORDER BY 2 DESC"
        };
        let mut stmt = db.prepare(sql)?;
        let rows = stmt
            .query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?)))?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    pub async fn count_detections(&self, include_operator: bool) -> Result<i64> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT COUNT(*) FROM detections"
        } else {
            "SELECT COUNT(*) FROM detections d
             JOIN events e ON e.id = d.event_id
             WHERE e.is_operator = 0"
        };
        let n: i64 = db.query_row(sql, [], |r| r.get(0))?;
        Ok(n)
    }

    /// Event counts split by attack surface: `(mcp, probe)`. The probe surface
    /// is everything logged from a non-MCP path (`method = 'probe'`, the
    /// `/.env` / `/.git` / `/admin` scan traffic); the MCP surface is the real
    /// protocol interactions. Keeping them apart stops commodity web scanning
    /// from inflating the numbers that should describe MCP-targeted threat.
    pub async fn count_events_by_surface(&self, include_operator: bool) -> Result<(i64, i64)> {
        let db = self.inner.db.lock().await;
        let op = if include_operator {
            ""
        } else {
            " AND is_operator = 0"
        };
        let mcp: i64 = db.query_row(
            &format!("SELECT COUNT(*) FROM events WHERE method != 'probe'{op}"),
            [],
            |r| r.get(0),
        )?;
        let probe: i64 = db.query_row(
            &format!("SELECT COUNT(*) FROM events WHERE method = 'probe'{op}"),
            [],
            |r| r.get(0),
        )?;
        Ok((mcp, probe))
    }

    /// Detection counts split by the parent event's surface: `(mcp, probe)`.
    pub async fn count_detections_by_surface(&self, include_operator: bool) -> Result<(i64, i64)> {
        let db = self.inner.db.lock().await;
        let op = if include_operator {
            ""
        } else {
            " AND e.is_operator = 0"
        };
        let mcp: i64 = db.query_row(
            &format!(
                "SELECT COUNT(*) FROM detections d JOIN events e ON e.id = d.event_id
                 WHERE e.method != 'probe'{op}"
            ),
            [],
            |r| r.get(0),
        )?;
        let probe: i64 = db.query_row(
            &format!(
                "SELECT COUNT(*) FROM detections d JOIN events e ON e.id = d.event_id
                 WHERE e.method = 'probe'{op}"
            ),
            [],
            |r| r.get(0),
        )?;
        Ok((mcp, probe))
    }

    /// Top N tool names called via `tools/call`, derived by extracting
    /// `params.name` from the stored JSON.
    pub async fn top_tools(
        &self,
        limit: i64,
        include_operator: bool,
    ) -> Result<Vec<(String, i64)>> {
        let db = self.inner.db.lock().await;
        let sql = if include_operator {
            "SELECT json_extract(params, '$.name') AS tool, COUNT(*) AS n
             FROM events WHERE method = 'tools/call' AND tool IS NOT NULL
             GROUP BY tool ORDER BY n DESC LIMIT ?1"
        } else {
            "SELECT json_extract(params, '$.name') AS tool, COUNT(*) AS n
             FROM events WHERE method = 'tools/call' AND tool IS NOT NULL
                   AND is_operator = 0
             GROUP BY tool ORDER BY n DESC LIMIT ?1"
        };
        let mut stmt = db.prepare(sql)?;
        let rows = stmt
            .query_map(params![limit], |r| {
                Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?))
            })?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    /// One-row-per-event view of the most recent sessions, used by the
    /// dashboard timeline. The dashboard groups these on the template
    /// side keyed by session_id; we don't pre-aggregate here so the same
    /// query feeds both the per-session view and the live feed without
    /// fanning out into multiple SQL paths.
    pub async fn recent_events_with_detections(
        &self,
        max_sessions: i64,
        include_operator: bool,
    ) -> Result<Vec<RawEventRow>> {
        let db = self.inner.db.lock().await;

        let session_filter = if include_operator {
            ""
        } else {
            "AND e.is_operator = 0"
        };

        // Pull the most recent N session_ids (ordered by their newest event),
        // then pull every event in those sessions plus matching detections.
        // Two-step query keeps the inner select bounded; the dashboard never
        // wants more than ~50 sessions on a first paint.
        let sql = format!(
            "WITH recent_sessions AS (
               SELECT session_id, MAX(timestamp_ms) AS last_seen
               FROM events e
               WHERE 1=1 {session_filter}
               GROUP BY session_id
               ORDER BY last_seen DESC
               LIMIT ?1
             )
             SELECT
               e.id, e.timestamp_ms, e.session_id, e.method, e.params,
               e.client_name, e.client_version, e.response_summary,
               e.transport, e.remote_addr, e.user_agent, e.client_meta,
               e.persona, e.is_operator,
               (SELECT json_group_array(json_object(
                  'detector', d.detector,
                  'severity', d.severity,
                  'category', d.category,
                  'evidence', d.evidence,
                  'mitre_techniques', d.mitre_techniques
               ))
                FROM detections d WHERE d.event_id = e.id) AS detections_json
             FROM events e
             JOIN recent_sessions r USING (session_id)
             ORDER BY r.last_seen DESC, e.timestamp_ms ASC"
        );

        let mut stmt = db.prepare(&sql)?;
        let rows = stmt
            .query_map(params![max_sessions], |r| {
                Ok(RawEventRow {
                    id: r.get(0)?,
                    timestamp_ms: r.get(1)?,
                    session_id: r.get(2)?,
                    method: r.get(3)?,
                    params: r.get(4)?,
                    client_name: r.get(5)?,
                    client_version: r.get(6)?,
                    response_summary: r.get(7)?,
                    transport: r.get(8)?,
                    remote_addr: r.get(9)?,
                    user_agent: r.get(10)?,
                    client_meta: r.get(11)?,
                    persona: r.get(12)?,
                    is_operator: r.get::<_, i64>(13)? != 0,
                    detections_json: r.get(14)?,
                })
            })?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }

    /// Bounded event window with detections inlined. This is the analytics
    /// feed for dashboard panels that need "last 24h" style views rather than
    /// the session-card window used by [`Logger::recent_events_with_detections`].
    pub async fn events_with_detections_since(
        &self,
        since_ms: i64,
        limit: i64,
        include_operator: bool,
    ) -> Result<Vec<RawEventRow>> {
        let db = self.inner.db.lock().await;
        let op_filter = if include_operator {
            ""
        } else {
            "AND e.is_operator = 0"
        };
        let sql = format!(
            "SELECT
               e.id, e.timestamp_ms, e.session_id, e.method, e.params,
               e.client_name, e.client_version, e.response_summary,
               e.transport, e.remote_addr, e.user_agent, e.client_meta,
               e.persona, e.is_operator,
               (SELECT json_group_array(json_object(
                  'detector', d.detector,
                  'severity', d.severity,
                  'category', d.category,
                  'evidence', d.evidence,
                  'mitre_techniques', d.mitre_techniques
               ))
                FROM detections d WHERE d.event_id = e.id) AS detections_json
             FROM events e
             WHERE e.timestamp_ms >= ?1 {op_filter}
             ORDER BY e.timestamp_ms DESC
             LIMIT ?2"
        );

        let mut stmt = db.prepare(&sql)?;
        let rows = stmt
            .query_map(params![since_ms, limit], |r| {
                Ok(RawEventRow {
                    id: r.get(0)?,
                    timestamp_ms: r.get(1)?,
                    session_id: r.get(2)?,
                    method: r.get(3)?,
                    params: r.get(4)?,
                    client_name: r.get(5)?,
                    client_version: r.get(6)?,
                    response_summary: r.get(7)?,
                    transport: r.get(8)?,
                    remote_addr: r.get(9)?,
                    user_agent: r.get(10)?,
                    client_meta: r.get(11)?,
                    persona: r.get(12)?,
                    is_operator: r.get::<_, i64>(13)? != 0,
                    detections_json: r.get(14)?,
                })
            })?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    }
}

/// Wide row returned by [`Logger::recent_events_with_detections`]. Stays
/// out of the public LogEntry API because it carries the inlined
/// detection JSON aggregate that only the dashboard wants.
#[derive(Debug, Clone)]
pub struct RawEventRow {
    pub id: i64,
    pub timestamp_ms: i64,
    pub session_id: String,
    pub method: String,
    pub params: Option<String>,
    pub client_name: Option<String>,
    pub client_version: Option<String>,
    pub response_summary: String,
    pub transport: Option<String>,
    pub remote_addr: Option<String>,
    pub user_agent: Option<String>,
    pub client_meta: Option<String>,
    pub persona: Option<String>,
    pub is_operator: bool,
    pub detections_json: Option<String>,
}

#[derive(Debug, Clone)]
pub struct CanaryBackfillEvent {
    pub event_id: i64,
    pub timestamp_ms: i64,
    pub persona: Option<String>,
    pub params: Option<String>,
}

#[derive(Debug, Clone)]
pub struct CanaryCorrelationRow {
    pub hit_id: i64,
    pub hit_timestamp_ms: i64,
    pub token_type: Option<String>,
    pub provider_event: Option<String>,
    pub later_token_use_ip: Option<String>,
    pub hit_user_agent: Option<String>,
    pub account_id: Option<String>,
    pub hit_marker: Option<String>,
    pub canary_marker: String,
    pub event_id: i64,
    pub exposure_timestamp_ms: i64,
    pub exposure_source_ip: Option<String>,
    pub persona: Option<String>,
    pub method: String,
    pub params: Option<String>,
    pub response_summary: String,
    pub delay_ms: i64,
}

fn add_column_if_missing(db: &Connection, table: &str, column: &str, col_type: &str) -> Result<()> {
    let existing: Vec<String> = db
        .prepare(&format!("PRAGMA table_info({table})"))?
        .query_map([], |r| r.get::<_, String>(1))?
        .filter_map(|r| r.ok())
        .collect();
    if existing.iter().any(|c| c == column) {
        return Ok(());
    }
    db.execute(
        &format!("ALTER TABLE {table} ADD COLUMN {column} {col_type}"),
        [],
    )
    .with_context(|| format!("adding column {column} to {table}"))?;
    Ok(())
}

pub fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[tokio::test]
    async fn records_events_to_sqlite_and_jsonl() {
        let dir = tempdir().unwrap();
        let db = dir.path().join("hive.db");
        let jsonl = dir.path().join("hive.jsonl");
        let logger = Logger::open(&db, Some(&jsonl)).await.unwrap();

        let entry = LogEntry {
            timestamp_ms: now_ms(),
            method: "tools/call".into(),
            params_hash: hash_params(&Some(serde_json::json!({"name": "query"}))),
            params: Some(serde_json::json!({"name": "query"})),
            client_name: Some("attacker".into()),
            client_version: Some("1.0".into()),
            session_id: "sess-1".into(),
            response_summary: "rows=0".into(),
            transport: Some("http".into()),
            remote_addr: Some("203.0.113.7:54321".into()),
            user_agent: Some("curl/8.0".into()),
            client_meta: Some(serde_json::json!({"x_forwarded_for": "198.51.100.9"})),
            persona: Some("test-persona".into()),
            is_operator: false,
        };
        logger.record(&entry).await.unwrap();

        assert_eq!(logger.count_events(false).await.unwrap(), 1);
        let body = tokio::fs::read_to_string(&jsonl).await.unwrap();
        assert!(body.contains("\"method\":\"tools/call\""));
        assert!(body.contains("\"client_name\":\"attacker\""));
        assert!(body.contains("\"transport\":\"http\""));
        assert!(body.contains("\"remote_addr\":\"203.0.113.7:54321\""));
    }

    #[tokio::test]
    async fn migrates_existing_db_in_place() {
        let dir = tempdir().unwrap();
        let db_path = dir.path().join("legacy.db");

        // Simulate an existing Day-1 schema that lacks the new columns.
        {
            let c = Connection::open(&db_path).unwrap();
            c.execute_batch(
                r#"
                CREATE TABLE events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp_ms INTEGER NOT NULL,
                    session_id TEXT NOT NULL,
                    method TEXT NOT NULL,
                    params_hash TEXT NOT NULL,
                    params TEXT,
                    client_name TEXT,
                    client_version TEXT,
                    response_summary TEXT NOT NULL
                );
                INSERT INTO events
                    (timestamp_ms, session_id, method, params_hash, response_summary)
                VALUES (1, 'old', 'initialize', 'h', 'ok');
                "#,
            )
            .unwrap();
        }

        // Opening via Logger must add the new columns without losing the old row.
        let logger = Logger::open(&db_path, None).await.unwrap();
        assert_eq!(logger.count_events(true).await.unwrap(), 1);

        let entry = LogEntry {
            timestamp_ms: 2,
            method: "tools/list".into(),
            params_hash: "h2".into(),
            params: None,
            client_name: None,
            client_version: None,
            session_id: "new".into(),
            response_summary: "ok".into(),
            transport: Some("http".into()),
            remote_addr: Some("127.0.0.1:1".into()),
            user_agent: None,
            client_meta: None,
            persona: None,
            is_operator: false,
        };
        logger.record(&entry).await.unwrap();
        assert_eq!(logger.count_events(true).await.unwrap(), 2);
    }

    #[tokio::test]
    async fn count_events_excludes_operator_rows_by_default() {
        let dir = tempdir().unwrap();
        let logger = Logger::open(&dir.path().join("h.db"), None).await.unwrap();

        let mut external = LogEntry {
            timestamp_ms: 1,
            method: "tools/list".into(),
            params_hash: "h".into(),
            params: None,
            client_name: None,
            client_version: None,
            session_id: "ext".into(),
            response_summary: "ok".into(),
            transport: Some("http".into()),
            remote_addr: Some("8.8.8.8:443".into()),
            user_agent: Some("curl/8.0".into()),
            client_meta: None,
            persona: Some("test-persona".into()),
            is_operator: false,
        };
        logger.record(&external).await.unwrap();

        external.session_id = "op".into();
        external.is_operator = true;
        external.user_agent = Some("honeymcp-probes/0.5.0".into());
        logger.record(&external).await.unwrap();

        assert_eq!(logger.count_events(false).await.unwrap(), 1);
        assert_eq!(logger.count_events(true).await.unwrap(), 2);
    }

    #[test]
    fn hash_is_stable_for_identical_params() {
        let a = Some(serde_json::json!({"k": 1}));
        assert_eq!(hash_params(&a), hash_params(&a));
        assert_ne!(hash_params(&a), hash_params(&None));
    }

    #[tokio::test]
    async fn correlates_canary_hits_to_exposure_events() {
        let dir = tempdir().unwrap();
        let logger = Logger::open(&dir.path().join("h.db"), None).await.unwrap();

        let entry = LogEntry {
            timestamp_ms: 1_000,
            method: "tools/call".into(),
            params_hash: hash_params(&Some(serde_json::json!({
                "name": "get_secret_value",
                "arguments": {"secret_name": "prod/rds/master"}
            }))),
            params: Some(serde_json::json!({
                "name": "get_secret_value",
                "arguments": {"secret_name": "prod/rds/master"}
            })),
            client_name: Some("probe".into()),
            client_version: Some("1.0".into()),
            session_id: "sess-canary".into(),
            response_summary: "tools/call name=get_secret_value".into(),
            transport: Some("http".into()),
            remote_addr: Some("202.182.104.22".into()),
            user_agent: Some("MCPProbe/1.0".into()),
            client_meta: None,
            persona: Some("aws-admin".into()),
            is_operator: false,
        };
        let event_id = logger.record(&entry).await.unwrap();
        logger
            .record_canary_exposures(event_id, 1_000, &["aws_sm_akid".into()])
            .await
            .unwrap();

        let hit = CanaryHit {
            observed_at_ms: 61_000,
            token_type: Some("aws_keys".into()),
            provider_event: Some("GetCallerIdentity".into()),
            later_token_use_ip: Some("209.250.120.16".into()),
            user_agent: Some("Boto3/1.43.10".into()),
            account_id: Some("194031983756".into()),
            input_channel: Some("web".into()),
            alert_status: Some("open".into()),
            marker: Some("aws_sm_akid".into()),
            geo_json: None,
            raw_hash: "a".repeat(64),
        };
        let summary = logger
            .import_canary_hits(std::slice::from_ref(&hit))
            .await
            .unwrap();
        assert_eq!(summary.inserted, 1);
        let summary = logger.import_canary_hits(&[hit]).await.unwrap();
        assert_eq!(summary.ignored, 1);

        let rows = logger
            .recent_canary_correlations(0, 24 * 60 * 60 * 1000, 10, false)
            .await
            .unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].event_id, event_id);
        assert_eq!(rows[0].canary_marker, "aws_sm_akid");
        assert_eq!(
            rows[0].later_token_use_ip.as_deref(),
            Some("209.250.120.16")
        );
        assert_eq!(rows[0].delay_ms, 60_000);
    }
}
